services:
  victim:
    image: nginx:alpine
    container_name: victim
    ports:
    - "8080:80"
  
  cap:
    image: nicolaka/netshoot
    container_name: cap
    network_mode: "service:victim"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./capture:/capture
    command: tcpdump -i any -w /capture/test.pcap
    depends_on:
    - victim

